import { Poppins } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'

const poppins = Poppins({weight: ['400', '600', '700'], subsets: ['latin']})

export const metadata = {
  title: 'Mastercard Landing Page',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      
      <body className={poppins.className}>
        <Header/>
        {children}
        </body>
    </html>
  )
}
